import { Poll } from '@/types/poll';

export const DEFAULT_POLLS: Poll[] = [
  {
    id: 'poll-1',
    code: '101010',
    title: 'Quanto sei d\'accordo con questa affermazione?',
    description: 'Valuta da 1 (per nulla) a 10 (completamente d\'accordo)',
    type: 'rating',
    min: 1,
    max: 10,
    minLabel: 'Per nulla d\'accordo',
    maxLabel: 'Totalmente d\'accordo',
    createdAt: Date.now() - 50000,
  },
  {
    id: 'poll-2',
    code: '202020',
    title: 'Cosa ti incuriosisce di più di questo argomento?',
    description: 'Scrivi 1 o 2 parole chiave (visibili in tempo reale)',
    type: 'text',
    maxLength: 80,
    placeholder: 'Es: Applicazioni pratiche, Futuro dell\'AI...',
    allowMultipleSubmissions: true,
    createdAt: Date.now() - 40000,
  },
  {
    id: 'poll-3',
    code: '303030',
    title: 'Quale soluzione adotteresti in questo scenario?',
    description: 'Scegli l\'opzione che ritieni più efficace',
    type: 'choice',
    options: [
      'Ottimizzazione dei processi esistenti',
      'Ridisegno completo dell\'architettura',
      'Approccio incrementale e modulare',
      'Test su campione pilota ristretto'
    ],
    createdAt: Date.now() - 30000,
  },
  {
    id: 'poll-4',
    code: '404040',
    title: 'Domande & Risposte per il relatore',
    description: 'Invia una domanda anonima o vota con 👍 le domande dei colleghi',
    type: 'qna',
    allowUpvotes: true,
    createdAt: Date.now() - 20000,
  },
  {
    id: 'poll-5',
    code: '505050',
    title: 'Come va il livello di energia e attenzione della sala?',
    description: 'Tocca un\'emoji per farla apparire sullo schermo!',
    type: 'emoji',
    emojis: ['🚀', '💡', '🔥', '🤔', '☕', '👏'],
    createdAt: Date.now() - 10000,
  },
  {
    id: 'poll-6',
    code: '606060',
    title: 'Possiamo passare al tema successivo?',
    description: 'Votazione rapida per il ritmo della presentazione',
    type: 'yesno',
    yesLabel: 'Sì, procediamo! 🚀',
    noLabel: 'Rivediamo un attimo ✋',
    maybeLabel: 'Solo una precisazione 💬',
    createdAt: Date.now(),
  },
];
